# Render Blueprint
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: asia-motor-score-streamlit
    env: python
    plan: free  # switch to 'starter' for always-on
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port $PORT --server.headless true"
    autoDeploy: true

# Optional: set PYTHON_VERSION if needed
# envVars:
#   - key: PYTHON_VERSION
#     value: "3.11"
